### PR TITLE
Fix incorrect value in lookup table

### PR DESCRIPTION
**Pull request by prplz**
Hi there, I noticed while testing this out on minecraft 1.4.6 that the experience tables are incorrect for levels higher than 31.
http://www.minecraftwiki.net/wiki/Experience#Leveling_Up

### CODE REVIEW

**Comment by aadnk** [comment]
Curious. If you print the content of the _xpTotalToReachLevel_ array with the current version of ExperienceMod, you get the following:

```
25: 560
26: 607
27: 657
28: 710
29: 766
30: 825
31: 887
32: 956
33: 1032
34: 1115
35: 1205
36: 1302
```

This is actually perfectly in sync with the table on Minecraft Wiki. However, in EntityHuman.java#1273, the equation seems to use 30 like in your commit:

```
public int getExpToLevel() {
    return this.expLevel >= 15 ? 17 + (this.expLevel - 15) * 3 : this.expLevel >= 30 ? 62 + (this.expLevel - 30) * 7 : 17;
}
```

This is also the value used by [desht](https://github.com/desht/dhutils/commit/1a29ada25d5a297ed226ee0b87cb0121f228379b) in his ExperienceManager, which is what I based my version on.

So, it seems that the Minecraft Wiki is wrong. The table should really read the following:

```
25: 560
26: 607
27: 657
28: 710
29: 766
30: 825
31: 891
32: 964
33: 1044
34: 1131
35: 1225
36: 1326
```

I think I might update it. In the meantime, I'll accept this commit. I should probably think about pushing a new version too. 

Here's the [code](https://gist.github.com/4529785) I used to generate the tables above.

**Comment by prplz** [comment]
Yay my first ever pr :excited:
Thanks for the awesome plugin by the way :)

**Comment by aadnk** [comment]
Actually, it appears that the original code was correct. I should have tested the original Minecraft code more thoroughly. as well as using code from CraftBukkit (or MCP) and not JD-GUI. Here's a program that prints the actual (though approximate) experience in between each level:
https://gist.github.com/4546090

I also wrote some code for checking this in Minecraft directly:

```
public class ExampleMod extends JavaPlugin {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (sender instanceof Player) {
            Player player = (Player) sender;
            int level = player.getLevel();
            int expFromLast = 0;

            player.setExp(0);

            while (player.getLevel() == level) {
                player.giveExp(1);
                expFromLast++;
            }

            getLogger().info(player.getLevel() + ": " + expFromLast);
        }

        return true;
    }
}
```

Which gives the following output:

```
[ExamplePlugin] 28: 54
[ExamplePlugin] 29: 57
[ExamplePlugin] 30: 59
[ExamplePlugin] 31: 63
[ExamplePlugin] 32: 70
[ExamplePlugin] 33: 76
[ExamplePlugin] 34: 84
[ExamplePlugin] 35: 90
[ExamplePlugin] 36: 97
[ExamplePlugin] 37: 105
[ExamplePlugin] 38: 112
[ExamplePlugin] 39: 118
[ExamplePlugin] 40: 125
```

So what exactly made you think the tables were wrong?

And sorry, but I will have to revert this commit then.

**Comment by prplz** [comment]
Ok maybe it's not the tables, but something is very wrong above level 30 here. I tried this on server (craftbukkit-1.4.6-R0.3) with only ExperienceMod.
I want players to drop all the experience on death so I have this in config.yml:

<pre>
player death:
  ?: EXPERIENCE
</pre>

Then I set my level to something under 30, and kill myself. I come back to the exp orbs and pickup the same amount that I had before. But when my level is above 30 I am picking up more exp than I died with.

**Comment by prplz** [comment]
<pre>
>xp 300 prplz
06:25:12 [INFO] CONSOLE: Given 300 experience to prplz
06:25:18 [INFO] prplz issued server command: /kill
06:25:18 [INFO] [ExperienceMod] Generated: 300 experience
06:25:18 [INFO] [ExperienceMod] Entity 329: Changed experience drop to 300 experience.
06:25:18 [INFO] [ExperienceMod] prplz took 300 experience loss.
06:25:18 [INFO] prplz died
</pre>

Ok, I dropped 300 experience as expected
Then I increase my exp by 600 - to 900 total and i drop 909

<pre>
>xp 600 prplz
06:26:30 [INFO] CONSOLE: Given 600 experience to prplz
06:26:36 [INFO] prplz issued server command: /kill
06:26:36 [INFO] [ExperienceMod] Generated: 909 experience
06:26:36 [INFO] [ExperienceMod] Entity 329: Changed experience drop to 909 experience.
06:26:36 [INFO] [ExperienceMod] prplz took 909 experience loss.
06:26:36 [INFO] prplz died
</pre>

My commit fixed this issue perfectly as far as I could see.

**Comment by aadnk** [comment]
Ok, this is just weird.

So I gave myself 900 experience from an initial zero experience, and I ended up at level 31 with about 3.4 / 18 (18.8%) on the experience bar.

In ExperienceMod I calculate the player's experience like so:

```
public int getCurrentExp() {
    Player player = getPlayer();

    int lvl = player.getLevel();
    int cur = getXpForLevel(lvl) + (int) Math.round(xpRequiredForNextLevel[lvl] * player.getExp());
    return cur;
}
```

If I input 31 as level and 3.4 as getExp(), I get 905. However, if I change initLookupTables() 30 to 31 like in your commit, it's actually down to 900.

Someone should really fix JD-GUI ...

And I should be a little more reserved before pushing new commits ...

**Comment by prplz** [comment]
Ok so... is my commit right or is there some deeper problem here?

**Comment by aadnk** [comment]
I suppose it's right, though there might be more problems in the experience system ...

Reverting a revert is a bit silly, but oh well.

**Comment by prplz** [comment]
You should also take a look at some of the other commits on my fork. The currency player parameter doesn't work at all on your version. Also player groups are not working. Also there are issues with minecraft stacking items together and some can lose their data somewhat when "economy drop worth" is higher than one.

**Pull request merged**
